import { Course } from './definitions';

export const MOCK_COURSES: Course[] = [
  // INFORMATION SECURITY & ASSURANCE CURRICULUM
  {
    id: '1',
    code: 'AUN 101',
    title: 'AUN 101 First Year Experience',
    description: 'Introduction to university life and academic success strategies',
    category: 'First Year Experience',
    department: 'Information Security & Assurance',
    school: 'School of IT and Computing',
    catalog: '2018',
    duration: 1,
    credits: 3,
    difficulty: 'beginner',
    requirements: [],
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    code: 'INF 351',
    title: 'INF 351 Info Security and Auditing',
    description: 'Information Security and Auditing',
    category: 'Information Security',
    department: 'Information Security & Assurance',
    school: 'School of IT and Computing',
    catalog: '2018',
    duration: 3,
    credits: 3,
    difficulty: 'advanced',
    requirements: [],
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
  // ... (rest of the course data)
  {
    id: '45',
    code: 'ELE 300',
    title: 'Free Elective Course 3',
    description: 'Choose any course of interest',
    category: 'Free Elective',
    department: 'Information Security & Assurance',
    school: 'School of IT and Computing',
    catalog: '2018',
    duration: 3,
    credits: 3,
    difficulty: 'beginner',
    requirements: [],
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-01-15T00:00:00Z',
  },
];
